export const HOME_COPY = {
  zh: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · REPRODUCIBLE',
    title: ['ScienceX', '科研孪生实验台'],
    heroThesis: '在数字空间复现研究，在证据回流中推进下一轮。',
    intro: 'ScienceX 把研究对象、实验条件与证据映射成可运行、可重放、可比较的数字实验。它锁定数据与实验版本，调用经过授权的模型和工具，并从证据差异中形成下一轮候选方向。',
    download: '下载 ScienceX',
    demo: '运行内置孪生案例',
    twinLink: '了解孪生如何工作',
    loopLink: '查看孪生闭环',
    releaseNote: '最新科研功能请以 Release 说明为准',
    trustLabel: 'ScienceX 产品特征',
    trust: ['本地优先', '版本锁定', '确定性重放', '人工确认'],
    proofAria: 'ScienceX 模拟细胞活力教学案例',
    proofLabel: '当前已验证 · 模拟教学案例',
    proofQuestionLabel: '研究问题',
    proofQuestion: 'SX-101 是否随浓度升高降低 HepG2 细胞的相对活力？',
    proofDataset: '锁定实验版本',
    proofRun: '确定性 4PL 运行',
    proofEvidence: '技术证据回流',
    proofVerdict: '拟合质量',
    proofIc50: '相对 IC50',
    proofReplay: '重放验证一致',
    proofArtifacts: '3 个研究产物',
    navLabel: '首页章节',
    navItems: [
      ['孪生是什么', '#research-twin'],
      ['当前案例', '#runnable-evidence'],
      ['如何运行', '#research-loop'],
      ['下一步启发', '#research-insight'],
      ['能力与连接', '#capabilities'],
      ['研究者角色', '#human-in-the-loop'],
      ['演进阶段', '#maturity'],
      ['开始', '#start'],
    ],
    twinNumber: '01',
    twinLabel: 'RESEARCH TWIN',
    twinTitle: ['把研究过程', '变成可运行的科研孪生'],
    twinBody: '围绕一个细分研究对象，ScienceX 把问题、数据、实验、运行证据和研究决策组织成持续对应的数字研究状态。每一轮都能检查版本、比较差异，并回到下一轮问题。',
    twinAria: 'ScienceX 科研孪生五层结构',
    twinContrastLabel: 'RESEARCH TWIN ≠ VISUALIZATION',
    twinContrastTitle: '科研孪生不是实验截图，也不只是一张流程图',
    twinContrastBody: '只有当研究对象、实验条件、执行过程、结果证据与研究决策保持可追溯对应，并能够再次运行与比较时，才形成一个可用的科研孪生。',
    twinLayers: [
      { code: '01', label: 'OBJECT', title: '对象层', body: '研究对象、科学问题、观测变量与数据结构。' },
      { code: '02', label: 'EXPERIMENT', title: '实验层', body: '变量、对照、实验条件、协议版本与验收标准。' },
      { code: '03', label: 'EXECUTION', title: '执行层', body: '模型、算法、工具、参数、运行环境与授权状态。' },
      { code: '04', label: 'EVIDENCE', title: '证据层', body: '输入、输出、日志、来源、哈希、失败与不确定性。' },
      { code: '05', label: 'DECISION', title: '决策层', body: '经研究者确认的边界、未解决问题与下一轮假设。' },
    ],
    twinEquationLabel: 'MINIMUM VIABLE TWIN',
    twinEquationTerms: ['对象表示', '版本化实验', '可重放运行', '证据回流', '人工决策'],
    twinBoundary: '有结果但没有条件与版本，不是孪生；有流程但没有可重放证据，也不是孪生。',
    realityNumber: '07',
    realityLabel: 'DAILY RESEARCH',
    realityTitle: ['让日常工作', '支撑科研孪生持续运行'],
    realityBody: '检索、整理、审查和表达不再散落在不同工具里，而是为同一研究对象补充证据、维护状态并形成可复核产物。研究者仍然保留阅读、判断和方向。',
    scenarioOutputLabel: '形成产物',
    scenarioOwnerLabel: '研究者保留',
    scenarioPromptLabel: '示例指令',
    realitySignals: [
      {
        title: '搜索资料',
        body: '按范围、来源、年份和验收格式检索并初筛。',
        output: '带出处的文献表与证据摘要',
        owner: '决定精读什么、相信什么',
        prompt: '检索近三年关于 X 的代表论文，每条附出处。',
      },
      {
        title: '进度跟踪',
        body: '把计划中、进行中、已完成和搁置事项归入研究线程。',
        output: '进度板、阶段总结与下一步清单',
        owner: '决定优先级和研究方向',
        prompt: '汇总本周推进、阻塞原因和下周最重要的三步。',
      },
      {
        title: '理清逻辑',
        body: '围绕前提、证据、反例和适用边界逐句追问。',
        output: '论证缺口与待验证问题',
        owner: '回答关键问题、修正论证',
        prompt: '扮演严格评审，追问这段论证凭什么成立。',
      },
      {
        title: '修改表达',
        body: '纠错、润色、统一术语，并保留修改类型与理由。',
        output: '修改建议、差异记录与风格档案',
        owner: '保留观点、结论和个人风格',
        prompt: '逐处给出原句、改句和理由，不替我改写结论。',
      },
    ],
    realityThesis: '重复工作只有进入同一研究状态，才不会在聊天、文件、代码和实验记录之间丢失上下文。',
    productNumber: '06',
    productLabel: 'PRODUCT IN USE',
    productTitle: ['孪生不只存在于概念图', '它运行在当前工作台里'],
    productBody: '研究项目、线程、定时任务与科研 Skills 承载孪生的日常运行。下面展示的是经过裁切和脱敏的当前产品界面。',
    productFrames: [
      {
        code: '01',
        label: 'RESEARCH THREAD',
        title: '研究线程承载问题与下一步',
        body: '把研究问题、过程说明、文件和后续行动放在同一条可继续的研究记录中。',
        image: '/images/home/research-thread.webp',
        alt: 'ScienceX 研究线程界面，展示分步骤研究行动和输入框',
      },
      {
        code: '02',
        label: 'SCHEDULED TASKS',
        title: '重复整理可以按计划运行',
        body: '在桌面端创建和管理定时任务；本地任务仅在应用运行、设备保持唤醒时执行。',
        image: '/images/home/scheduled-tasks.webp',
        alt: 'ScienceX 定时任务界面，展示新建任务入口和本地运行提示',
      },
    ],
    productSkillLabel: 'RESEARCH SKILLS',
    productSkillTitle: '方法不是隐藏提示词，而是可查看的能力',
    productSkillBody: '科研 Skills 在产品中独立呈现，研究者可以查看名称、来源和适用边界。',
    productSkillPreview: ['scansci-pdf', 'good-question', 'experiment-design', 'academic-writing', 'papercheck', 'skill-criticagent'],
    productSkillCount: '20',
    productProofNote: '界面随版本持续更新；实际可用能力以当前 Release、本机依赖、连接状态与授权范围为准。',
    loopNumber: '03',
    loopLabel: 'TWIN LOOP',
    loopTitle: ['结果回到孪生状态', '研究才进入下一轮'],
    loopBody: 'ScienceX 当前能够形成研究者驱动的数字实验闭环：锁定版本、运行分析、保存技术证据并重放比较。接入经过校准的现实数据源后，实验反馈才能进一步更新科研孪生。',
    loopDiagramLabel: '从研究问题到下一轮问题的研究闭环',
    loopNodes: [
      { title: '研究问题', subtitle: 'Question' },
      { title: '候选假设', subtitle: 'Hypothesis' },
      { title: '证据与数据', subtitle: 'Evidence' },
      { title: '实验 / 计算', subtitle: 'Experiment' },
      { title: '结果与边界', subtitle: 'Result' },
      { title: '下一轮问题', subtitle: 'Next question' },
    ],
    loopCenter: 'Twin Loop',
    loopCenterBody: '证据差异更新研究状态',
    memoryTitle: 'Research Memory',
    memoryBody: '研究目标 · 候选假设 · 数据版本 · 证据关系 · 关键决策 · 结果 · 未解决问题',
    loopBoundary: '当前闭环由研究者驱动。ScienceX 协助执行、记录与重放，不替代最终科学判断。',
    feedbackLanes: [
      { tag: 'CURRENT · SOLID LINE', title: '数字实验闭环', body: '实验设计 → 锁定数据版本 → 确定性分析 → 技术证据 → Artifact → Replay', status: 'current' },
      { tag: 'CONNECT · DASHED LINE', title: '现实反馈通道', body: '实验设备 / ELN / LIMS / 人工观测 → 专用连接与校验 → 更新孪生状态', status: 'connect' },
    ],
    insightNumber: '04',
    insightLabel: 'EVIDENCE TO NEXT',
    insightTitle: ['启发不是凭空猜想', '而是从证据差异中产生下一步'],
    insightBody: 'ScienceX 比较不同版本、条件和运行结果，暴露证据缺口、敏感变量与冲突来源，形成可验证的候选假设和实验建议。研究者决定是否采用。',
    insightAria: 'ScienceX 从证据生成候选下一步的结构化示例',
    insightSignals: [
      { code: '01', title: '证据缺口', body: '识别缺少对照、重复、关键条件或来源支撑的结论。' },
      { code: '02', title: '参数敏感性', body: '比较哪些变量变化最可能改变当前运行结果。' },
      { code: '03', title: '跨运行差异', body: '追踪数据、设计、参数与结果在不同版本之间的变化。' },
      { code: '04', title: '外部证据冲突', body: '定位文献与本地结果在对象、条件或测量方法上的差异。' },
    ],
    insightExampleLabel: 'ILLUSTRATIVE CANDIDATE',
    insightExampleTitle: '弱响应之后，下一轮该验证什么？',
    insightRows: [
      { label: '观察', value: '当前运行完成，但剂量响应较弱，技术证据尚无定论。' },
      { label: '候选解释', value: '现有浓度范围可能没有覆盖可识别的响应区间。' },
      { label: '建议下一步', value: '扩展浓度范围，并在关键区间增加重复与对照。' },
      { label: '所需验证', value: '由研究者审核设计；真实实验或独立数据确认后才能更新科学判断。' },
    ],
    insightStatusLabel: 'DECISION STATE',
    insightStatus: '待研究者确认',
    insightBoundary: '候选下一步是基于技术证据的可验证建议，不是自主科学发现，也不会自动启动真实实验。',
    maturityNumber: '10',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: '从数字实验孪生，到现实反馈孪生',
    maturityBody: '首页把产品对象的成熟度与 AI 角色分开表达。当前已经验证数字实验孪生；领域数据、现实反馈与多路线自治属于后续阶段。',
    stages: [
      {
        tag: 'NOW',
        badge: '当前可用',
        title: '数字实验孪生',
        body: '版本化实验设计、锁定数据、确定性分析、技术证据、产物与重放。',
        logic: 'VERSION → RUN → EVIDENCE → REPLAY',
      },
      {
        tag: 'NEXT',
        badge: '下一阶段',
        title: '领域科研孪生',
        body: '为细分领域建立稳定的数据结构、专用模型、评价规则与持续研究状态。',
        logic: 'DOMAIN MODEL → CONTROLLED STATE',
      },
      {
        tag: 'CONNECT',
        badge: '需要专用连接',
        title: '现实反馈孪生',
        body: '通过经过验证的 ELN、LIMS、设备或观测数据连接器更新孪生状态。',
        logic: 'REAL FEEDBACK → VALIDATION → UPDATE',
      },
      {
        tag: 'VISION',
        badge: '长期愿景',
        title: '科研孪生网络',
        body: '并行比较多条候选研究路线，由研究者治理、合并、保留或停止。',
        logic: 'MULTI-PATH → COMPARE → DECIDE',
      },
    ],
    maturityBoundary: '当前不包含通用实验设备控制、无人值守湿实验或模型权重自动更新；MCP 只提供扩展接入口。',
    caseNumber: '02',
    caseLabel: 'CURRENT TWIN UNIT',
    caseTitle: '一个可以运行、失败和重放的实验孪生',
    caseBody: 'HepG2 × SX-101 教学案例在本地生成模拟数据，完成版本化实验设计、确定性 4PL 分析、技术证据评估和结果重放。它同时保留失败与证据不足。',
    caseFacts: [
      ['03 MIN', '本地教学案例'],
      ['24 WELLS', '带版本的实验设计'],
      ['SHA-256', '输入与产物哈希'],
      ['REPLAY', '固定原始版本重放'],
    ],
    scenariosTitle: '四种可复现运行结果',
    scenarios: [
      ['正常剂量反应', '完成分析并生成 3 个产物', 'passed'],
      ['数据更新', '旧版本仍可固定重放', 'verified'],
      ['缺孔输入', '明确失败，不静默补值', 'blocked'],
      ['弱响应', '运行完成，技术证据尚无定论', 'review'],
    ],
    simulationNote: '模拟数据，仅用于产品教学；不代表真实药效、湿实验验证或科学结论。',
    mechanismNumber: '05',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['ScienceX 如何承载', '一次孪生运行'],
    mechanismBody: '模型生成候选推理。ScienceX 编排已授权工具、记录输入输出并保存研究状态；关键判断由研究者完成。',
    mechanismAria: 'ScienceX 研究运行机制',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: '读取研究问题、研究线程与当前证据。' },
      { code: '02', title: 'Plan', body: '拆解任务，确定下一步执行路径。' },
      { code: '03', title: 'Act', body: '调用本机已安装且获得授权的能力。' },
      { code: '04', title: 'Verify', body: '检查输入、运行结果、告警与产物。' },
      { code: '05', title: 'Preserve', body: '经研究者确认后保存结论、边界与下一步。' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: '这里的“保存”是研究状态回流，不代表模型权重自动更新；自动化执行也不等于科学结论。',
    capabilitiesNumber: '08',
    capabilitiesLabel: 'RESEARCH SKILLS',
    capabilitiesTitle: ['20 个科研 Skills', '服务孪生的完整生命周期'],
    capabilitiesBody: 'Skills 用于建立、运行、验证和更新科研孪生。它们是可以检查的方法；运行条件、外部访问权和真实设备连接不会被隐含授予。',
    skillCount: '20',
    skillCountLabel: '个科研 Skills 已集成到 ScienceX',
    skillGroups: [
      {
        code: '01',
        title: '建立孪生',
        body: '定义研究对象、实验设计与可验证的数据基线。',
        skills: ['find-science-skills', 'experiment-design', 'research-baseline-builder'],
      },
      {
        code: '02',
        title: '补充证据',
        body: '检索论文、获取资料并形成可核对的研究证据。',
        skills: ['giiisp-paper-search-apis', 'scansci-pdf', 'sci-employee-deep-research'],
      },
      {
        code: '03',
        title: '生成候选',
        body: '从证据差异形成候选方向，并用评审式追问暴露缺口。',
        skills: ['scispark', 'good-question'],
      },
      {
        code: '04',
        title: '形成研究产物',
        body: '组织论文、图像、幻灯片、视频与课程产物。',
        skills: ['academic-writing', 'scientific-humanization', 'giiisp-scientific-image-generation', 'visual-deck-builder', 'manim-agent', 'practical-course-producer'],
      },
      {
        code: '05',
        title: '验证与更新',
        body: '检查论文和引用，并保存经确认的长期研究状态。',
        skills: ['thesis-audit-reviewer', 'papercheck', 'cognitive-profile', 'world-threads-entry'],
      },
      {
        code: '06',
        title: '评测与扩展',
        body: '采用新工具或连接器前检查 MCP 与 Skill 的质量。',
        skills: ['mcp-criticagent', 'skill-criticagent'],
      },
    ],
    environmentsLabel: '授权后连接执行环境',
    environments: [
      { title: '本地文件', body: 'PDF / CSV / 项目目录' },
      { title: '代码与终端', body: '仓库 / 命令 / 脚本' },
      { title: '模型提供商', body: '已配置的推理模型' },
      { title: 'MCP 服务', body: '已启用的扩展工具' },
      { title: '数据源', body: '经授权的数据库与服务' },
      { title: '计算环境', body: '本机已有的计算能力' },
    ],
    skillsBoundary: '“已集成”不等于无条件可运行。部分 Skills 需要本机依赖、外部服务或用户授权；ScienceX 不会默认获得论文库、数据库或其他系统的访问权。',
    skillsGuide: '查看 Skills 使用指南',
    humanNumber: '09',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX 负责执行与记录', '研究者负责判断与方向'],
    humanIntro: 'ScienceX 可以接手重复、可检查的执行工作，但不能替研究者选择可信证据、确认实验有效性或签署科学结论。高风险操作必须获得明确授权。',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['检索、阅读与整理', '编码、计算与比较', '执行获得授权的工具', '保存过程和候选假设'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['提出重要研究问题', '审核方案与关键证据', '判断结果是否成立', '决定下一轮研究方向'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · 研究者发起、授权、复核并作出最终判断',
    guardrailsLabel: 'ScienceX 使用边界',
    guardrails: ['AI 辅助表达，不代写结论', 'AI 帮助初筛，不代替精读', '敏感数据按边界处理', '技术证据不等于科学结论'],
    finalNumber: '11',
    finalTitle: '从第一个可运行的孪生单元开始',
    finalBody: '先运行内置模拟案例，理解版本、证据与重放；再用自己的研究对象定义一个可验证的数字实验。',
    startSteps: ['运行内置孪生案例', '定义研究对象、变量与验收标准', '检查证据并确认候选下一步'],
    starterPromptLabel: '接入研究对象的起始模板',
    starterPrompt: '我要围绕 X 建立科研孪生。研究对象是［对象］，输入数据是［格式与版本］，可调变量是［变量］，输出指标是［指标］，验收标准是［标准］。请先检查缺失条件，不要默认真实设备已经接入。',
    source: '查看源代码',
  },
  en: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · REPRODUCIBLE',
    title: ['ScienceX', 'Research Twin Workbench'],
    heroThesis: 'Reproduce research digitally. Move the next cycle forward as evidence returns.',
    intro: 'ScienceX maps research objects, experimental conditions, and evidence into digital experiments that can run, replay, and be compared. It pins data and experiment versions, invokes authorized models and tools, and turns evidence differences into candidate next directions.',
    download: 'Download ScienceX',
    demo: 'Run the built-in twin',
    twinLink: 'See how the twin works',
    loopLink: 'View the twin loop',
    releaseNote: 'Check each Release for the latest included research features',
    trustLabel: 'ScienceX product attributes',
    trust: ['Local first', 'Pinned versions', 'Deterministic replay', 'Human confirmation'],
    proofAria: 'ScienceX simulated cell-viability teaching example',
    proofLabel: 'VALIDATED NOW · SIMULATED TEACHING CASE',
    proofQuestionLabel: 'Research question',
    proofQuestion: 'Does SX-101 reduce HepG2 relative viability as concentration increases?',
    proofDataset: 'Pinned experiment version',
    proofRun: 'Deterministic 4PL run',
    proofEvidence: 'Evidence returned',
    proofVerdict: 'Fit quality',
    proofIc50: 'Relative IC50',
    proofReplay: 'Replay verified',
    proofArtifacts: '3 research artifacts',
    navLabel: 'Homepage sections',
    navItems: [
      ['What is a twin?', '#research-twin'],
      ['Current case', '#runnable-evidence'],
      ['How it runs', '#research-loop'],
      ['Next insight', '#research-insight'],
      ['Skills & connections', '#capabilities'],
      ['Researcher role', '#human-in-the-loop'],
      ['Maturity', '#maturity'],
      ['Start', '#start'],
    ],
    twinNumber: '01',
    twinLabel: 'RESEARCH TWIN',
    twinTitle: ['Turn the research process', 'into a runnable research twin'],
    twinBody: 'For a focused research object, ScienceX organizes the question, data, experiment, run evidence, and research decisions into a continuously corresponding digital state. Every cycle can expose its version, compare differences, and return to the next question.',
    twinAria: 'Five-layer ScienceX research twin architecture',
    twinContrastLabel: 'RESEARCH TWIN ≠ VISUALIZATION',
    twinContrastTitle: 'A research twin is neither an experiment screenshot nor a flowchart',
    twinContrastBody: 'A useful research twin exists only when the research object, experimental conditions, execution, evidence, and decisions remain traceably aligned and can be run and compared again.',
    twinLayers: [
      { code: '01', label: 'OBJECT', title: 'Object layer', body: 'Research object, scientific question, observables, and data structure.' },
      { code: '02', label: 'EXPERIMENT', title: 'Experiment layer', body: 'Variables, controls, conditions, protocol versions, and acceptance criteria.' },
      { code: '03', label: 'EXECUTION', title: 'Execution layer', body: 'Models, algorithms, tools, parameters, environments, and authorization state.' },
      { code: '04', label: 'EVIDENCE', title: 'Evidence layer', body: 'Inputs, outputs, logs, sources, hashes, failures, and uncertainty.' },
      { code: '05', label: 'DECISION', title: 'Decision layer', body: 'Researcher-approved boundaries, open questions, and next hypotheses.' },
    ],
    twinEquationLabel: 'MINIMUM VIABLE TWIN',
    twinEquationTerms: ['Object model', 'Versioned experiment', 'Replayable run', 'Evidence return', 'Human decision'],
    twinBoundary: 'A result without conditions and versions is not a twin. A workflow without replayable evidence is not a twin either.',
    realityNumber: '07',
    realityLabel: 'DAILY RESEARCH',
    realityTitle: ['Let daily work', 'keep the research twin running'],
    realityBody: 'Search, organization, review, and expression no longer disappear across disconnected tools. They add evidence, maintain state, and create reviewable artifacts for one research object while researchers retain close reading, judgment, and direction.',
    scenarioOutputLabel: 'Artifact',
    scenarioOwnerLabel: 'Researcher keeps',
    scenarioPromptLabel: 'Example prompt',
    realitySignals: [
      {
        title: 'Find sources',
        body: 'Search and screen by scope, source, date, and acceptance format.',
        output: 'A sourced paper table and evidence brief',
        owner: 'What deserves close reading and trust',
        prompt: 'Find representative papers on X from the last three years. Cite every item.',
      },
      {
        title: 'Track progress',
        body: 'Organize planned, active, completed, and paused work in the research thread.',
        output: 'Progress board, review, and next-step list',
        owner: 'Priority and research direction',
        prompt: 'Summarize this week, blockers, and the three most important next steps.',
      },
      {
        title: 'Trace logic',
        body: 'Interrogate premises, evidence, counterexamples, and scope one claim at a time.',
        output: 'Argument gaps and questions to verify',
        owner: 'Answers and changes to the argument',
        prompt: 'Act as a rigorous reviewer and ask what makes each claim hold.',
      },
      {
        title: 'Refine expression',
        body: 'Correct, polish, and normalize terms while recording each type of change.',
        output: 'Suggestions, diffs, and a style record',
        owner: 'Position, conclusion, and personal voice',
        prompt: 'Show original, revision, and reason. Do not rewrite my conclusion.',
      },
    ],
    realityThesis: 'Repetitive work becomes valuable when it updates a shared research state instead of losing context across chats, files, code, and experiment records.',
    productNumber: '06',
    productLabel: 'PRODUCT IN USE',
    productTitle: ['The twin is not just a concept diagram.', 'It runs inside today’s workbench.'],
    productBody: 'Research projects, threads, scheduled tasks, and research Skills carry the twin through daily work. These are cropped, privacy-safe views of the current product.',
    productFrames: [
      {
        code: '01',
        label: 'RESEARCH THREAD',
        title: 'A thread carries the question forward',
        body: 'Keep the research question, process notes, files, and proposed actions in one record that can continue.',
        image: '/images/home/research-thread.webp',
        alt: 'ScienceX research thread showing structured next actions and the prompt composer',
      },
      {
        code: '02',
        label: 'SCHEDULED TASKS',
        title: 'Recurring work can run on a schedule',
        body: 'Create and manage scheduled desktop tasks. Local tasks run only while the app is open and the device stays awake.',
        image: '/images/home/scheduled-tasks.webp',
        alt: 'ScienceX scheduled tasks screen with a create-task action and local runtime notice',
      },
    ],
    productSkillLabel: 'RESEARCH SKILLS',
    productSkillTitle: 'Methods are visible capabilities, not hidden prompts',
    productSkillBody: 'Research Skills appear independently in the product so researchers can inspect their names, sources, and operating boundaries.',
    productSkillPreview: ['scansci-pdf', 'good-question', 'experiment-design', 'academic-writing', 'papercheck', 'skill-criticagent'],
    productSkillCount: '20',
    productProofNote: 'The interface evolves by release. Actual availability depends on the current release, local dependencies, connection state, and authorization.',
    loopNumber: '03',
    loopLabel: 'TWIN LOOP',
    loopTitle: ['Results return to twin state.', 'Research enters the next cycle.'],
    loopBody: 'ScienceX currently provides a researcher-driven digital experiment loop: pin versions, run analyses, preserve technical evidence, and replay comparisons. Only after calibrated real-world sources are connected can experimental feedback update the research twin.',
    loopDiagramLabel: 'Research loop from a question to the next question',
    loopNodes: [
      { title: 'Question', subtitle: 'Research focus' },
      { title: 'Hypothesis', subtitle: 'Candidate explanation' },
      { title: 'Evidence', subtitle: 'Data and sources' },
      { title: 'Experiment', subtitle: 'Experiment / compute' },
      { title: 'Result', subtitle: 'Outcome and boundary' },
      { title: 'Next question', subtitle: 'Continue the loop' },
    ],
    loopCenter: 'Twin Loop',
    loopCenterBody: 'Evidence differences update research state',
    memoryTitle: 'Research Memory',
    memoryBody: 'Goals · candidate hypotheses · dataset versions · evidence relations · decisions · results · open questions',
    loopBoundary: 'The current loop is researcher-driven. ScienceX assists execution, recording, and replay; it does not replace the final scientific judgment.',
    feedbackLanes: [
      { tag: 'CURRENT · SOLID LINE', title: 'Digital experiment loop', body: 'Experiment design → pinned dataset → deterministic analysis → technical evidence → Artifact → Replay', status: 'current' },
      { tag: 'CONNECT · DASHED LINE', title: 'Real-world feedback channel', body: 'Instrument / ELN / LIMS / human observation → dedicated connection and validation → twin-state update', status: 'connect' },
    ],
    insightNumber: '04',
    insightLabel: 'EVIDENCE TO NEXT',
    insightTitle: ['Insight is not a random guess.', 'It emerges from differences in evidence.'],
    insightBody: 'ScienceX compares versions, conditions, and run outcomes to expose evidence gaps, sensitive variables, and sources of conflict. It produces testable candidate hypotheses and experiment suggestions for researcher review.',
    insightAria: 'Structured example of ScienceX turning evidence into a candidate next step',
    insightSignals: [
      { code: '01', title: 'Evidence gaps', body: 'Find claims that lack controls, replicates, critical conditions, or source support.' },
      { code: '02', title: 'Parameter sensitivity', body: 'Compare which variable changes are most likely to alter the current result.' },
      { code: '03', title: 'Cross-run differences', body: 'Trace changes in data, design, parameters, and outcomes across versions.' },
      { code: '04', title: 'External conflicts', body: 'Locate differences in object, conditions, or measurement between literature and local results.' },
    ],
    insightExampleLabel: 'ILLUSTRATIVE CANDIDATE',
    insightExampleTitle: 'After a weak response, what should the next cycle test?',
    insightRows: [
      { label: 'Observation', value: 'The run completed, but the dose response is weak and the technical evidence remains inconclusive.' },
      { label: 'Candidate account', value: 'The current concentration range may not cover an identifiable response region.' },
      { label: 'Proposed next step', value: 'Extend the concentration range and add replicates and controls around the critical region.' },
      { label: 'Required validation', value: 'A researcher reviews the design; only real experiments or independent data can update scientific judgment.' },
    ],
    insightStatusLabel: 'DECISION STATE',
    insightStatus: 'Awaiting researcher confirmation',
    insightBoundary: 'A candidate next step is a testable suggestion grounded in technical evidence. It is not autonomous discovery and does not start a real experiment automatically.',
    maturityNumber: '10',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: 'From a digital experiment twin to real-world feedback',
    maturityBody: 'The homepage separates product-object maturity from AI-role maturity. A digital experiment twin is validated now; domain structure, real feedback, and multi-path autonomy belong to later stages.',
    stages: [
      {
        tag: 'NOW',
        badge: 'Available now',
        title: 'Digital experiment twin',
        body: 'Versioned experiment designs, pinned data, deterministic analysis, technical evidence, artifacts, and replay.',
        logic: 'VERSION → RUN → EVIDENCE → REPLAY',
      },
      {
        tag: 'NEXT',
        badge: 'Next stage',
        title: 'Domain research twin',
        body: 'Stable data structures, specialist models, evaluation rules, and sustained research state for a focused domain.',
        logic: 'DOMAIN MODEL → CONTROLLED STATE',
      },
      {
        tag: 'CONNECT',
        badge: 'Dedicated connection',
        title: 'Real-world feedback twin',
        body: 'Update twin state through validated ELN, LIMS, instrument, or observational-data connectors.',
        logic: 'REAL FEEDBACK → VALIDATION → UPDATE',
      },
      {
        tag: 'VISION',
        badge: 'Long-term vision',
        title: 'Research twin network',
        body: 'Compare multiple candidate research paths in parallel while researchers govern, merge, retain, or stop them.',
        logic: 'MULTI-PATH → COMPARE → DECIDE',
      },
    ],
    maturityBoundary: 'The current product does not provide generic instrument control, unattended wet-lab operation, or automatic model-weight updates. MCP is an extension seam only.',
    caseNumber: '02',
    caseLabel: 'CURRENT TWIN UNIT',
    caseTitle: 'Not a concept diagram: an experiment twin that can run, fail, and replay',
    caseBody: 'The HepG2 × SX-101 teaching case generates simulated data locally, then runs a versioned experiment design, deterministic 4PL analysis, technical-evidence evaluation, and replay. It preserves failures and inconclusive evidence as well.',
    caseFacts: [
      ['03 MIN', 'Local teaching example'],
      ['24 WELLS', 'Versioned assay design'],
      ['SHA-256', 'Input and artifact hashes'],
      ['REPLAY', 'Pinned-version replay'],
    ],
    scenariosTitle: 'Four reproducible run outcomes',
    scenarios: [
      ['Dose response', 'Completes analysis and creates 3 artifacts', 'passed'],
      ['Changed data', 'The pinned old version still replays', 'verified'],
      ['Missing well', 'Fails explicitly without filling values', 'blocked'],
      ['Weak response', 'Run completes with inconclusive evidence', 'review'],
    ],
    simulationNote: 'Simulated teaching data. It does not establish efficacy, wet-lab validation, or a scientific conclusion.',
    mechanismNumber: '05',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['How ScienceX carries', 'one twin run'],
    mechanismBody: 'Models generate candidate reasoning. ScienceX orchestrates authorized tools, records inputs and outputs, and preserves research state; the researcher makes the important judgments.',
    mechanismAria: 'ScienceX research runtime mechanism',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: 'Read the question, research thread, and current evidence.' },
      { code: '02', title: 'Plan', body: 'Break down the task and define the next execution path.' },
      { code: '03', title: 'Act', body: 'Call capabilities installed locally and explicitly authorized.' },
      { code: '04', title: 'Verify', body: 'Inspect inputs, results, warnings, and artifacts.' },
      { code: '05', title: 'Preserve', body: 'Save conclusions, boundaries, and next steps after researcher confirmation.' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: 'Preserving research state does not update model weights automatically, and automated execution is not a scientific conclusion.',
    capabilitiesNumber: '08',
    capabilitiesLabel: 'RESEARCH SKILLS',
    capabilitiesTitle: ['20 research Skills.', 'Methods across the twin lifecycle.'],
    capabilitiesBody: 'Skills help build, run, verify, and update research twins. They are inspectable methods; runtime requirements, external access, and real-instrument connections are never implied.',
    skillCount: '20',
    skillCountLabel: 'research Skills integrated with ScienceX',
    skillGroups: [
      {
        code: '01',
        title: 'Build the twin',
        body: 'Define the research object, experiment design, and verifiable data baseline.',
        skills: ['find-science-skills', 'experiment-design', 'research-baseline-builder'],
      },
      {
        code: '02',
        title: 'Add evidence',
        body: 'Find papers, retrieve sources, and build evidence that can be checked.',
        skills: ['giiisp-paper-search-apis', 'scansci-pdf', 'sci-employee-deep-research'],
      },
      {
        code: '03',
        title: 'Generate candidates',
        body: 'Turn evidence differences into candidate directions and expose gaps through reviewer-style questions.',
        skills: ['scispark', 'good-question'],
      },
      {
        code: '04',
        title: 'Create research artifacts',
        body: 'Organize papers, figures, slides, videos, and course artifacts.',
        skills: ['academic-writing', 'scientific-humanization', 'giiisp-scientific-image-generation', 'visual-deck-builder', 'manim-agent', 'practical-course-producer'],
      },
      {
        code: '05',
        title: 'Verify & update',
        body: 'Review papers and citations while preserving researcher-approved long-running state.',
        skills: ['thesis-audit-reviewer', 'papercheck', 'cognitive-profile', 'world-threads-entry'],
      },
      {
        code: '06',
        title: 'Evaluate & extend',
        body: 'Assess MCP servers and Skills before adopting new tools or connectors.',
        skills: ['mcp-criticagent', 'skill-criticagent'],
      },
    ],
    environmentsLabel: 'Execution environments connect after authorization',
    environments: [
      { title: 'Local files', body: 'PDF / CSV / project folders' },
      { title: 'Code & terminal', body: 'Repositories / commands / scripts' },
      { title: 'Model providers', body: 'Configured reasoning models' },
      { title: 'MCP services', body: 'Enabled extension tools' },
      { title: 'Data sources', body: 'Authorized databases and services' },
      { title: 'Compute', body: 'Existing local compute capabilities' },
    ],
    skillsBoundary: 'Integrated does not mean universally runnable. Some Skills require local dependencies, external services, or user authorization. ScienceX has no default access to paper libraries, databases, or other systems.',
    skillsGuide: 'Read the Skills guide',
    humanNumber: '09',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX executes and records.', 'Researchers own judgment and direction.'],
    humanIntro: 'ScienceX can take on repetitive, reviewable execution. It cannot choose trusted evidence, validate an experiment, or sign off on a scientific conclusion for the researcher. High-risk actions require explicit authorization.',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['Search, read, and organize', 'Code, compute, and compare', 'Execute authorized tools', 'Preserve process and candidate hypotheses'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['Ask important research questions', 'Review protocols and critical evidence', 'Decide what the results support', 'Choose the next research direction'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · researchers initiate, authorize, review, and make the final judgment',
    guardrailsLabel: 'ScienceX operating boundaries',
    guardrails: ['AI assists expression; it does not author the conclusion', 'AI helps screen; it does not replace close reading', 'Sensitive data stays within defined boundaries', 'Technical evidence is not a scientific conclusion'],
    finalNumber: '11',
    finalTitle: 'Start with one runnable twin unit',
    finalBody: 'Run the built-in simulated case to understand versions, evidence, and replay. Then define a verifiable digital experiment for your own research object.',
    startSteps: ['Run the built-in twin case', 'Define the research object, variables, and acceptance criteria', 'Inspect evidence and confirm the candidate next step'],
    starterPromptLabel: 'Research-object onboarding template',
    starterPrompt: 'I want to build a research twin around X. The research object is [object], the input data are [format and version], the adjustable variables are [variables], the output metrics are [metrics], and the acceptance criteria are [criteria]. First identify missing conditions, and do not assume a real instrument is connected.',
    source: 'View source',
  },
} as const

export type HomeCopy = (typeof HOME_COPY)[keyof typeof HOME_COPY]
