export const HOME_COPY = {
  zh: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · TRACEABLE',
    title: ['让研究问题与证据', '始终指向下一步'],
    intro: 'ScienceX 是开源、本地优先的 AI 科研工作台。它保存研究上下文，调用经过授权的能力，并把数据版本、分析运行和研究产物留在同一条可追溯链路中。',
    download: '下载 ScienceX',
    demo: '体验 3 分钟案例',
    loopLink: '了解 Research Loop',
    releaseNote: '最新科研功能请以 Release 说明为准',
    trustLabel: 'ScienceX 产品特征',
    trust: ['本地数据', '开放源码', '跨平台桌面端'],
    proofAria: 'ScienceX 模拟细胞活力教学案例',
    proofLabel: '内置案例 · 模拟数据',
    proofQuestionLabel: '研究问题',
    proofQuestion: 'SX-101 是否随浓度升高降低 HepG2 细胞的相对活力？',
    proofDataset: '锁定数据版本',
    proofRun: '确定性 4PL 分析',
    proofEvidence: '技术证据',
    proofVerdict: '支持',
    proofIc50: '相对 IC50',
    proofReplay: '重放验证一致',
    proofArtifacts: '3 个研究产物',
    navLabel: '首页章节',
    navItems: [
      ['问题', '#research-reality'],
      ['闭环', '#research-loop'],
      ['案例', '#runnable-evidence'],
      ['机制', '#mechanism'],
      ['能力', '#capabilities'],
      ['边界', '#human-in-the-loop'],
    ],
    realityNumber: '01',
    realityLabel: 'ATTENTION',
    realityTitle: ['科研最稀缺的不是信息', '而是研究者的注意力'],
    realityBody: '科研工作被拆散在文献、代码、数据、实验软件和写作工具之间。真正昂贵的，是研究者持续搬运信息、重建上下文和追溯证据关系的时间。',
    realitySignals: [
      { title: '搜资料', body: '文献、数据与工具分散，时间耗在搜索和筛选。' },
      { title: '理进度', body: '任务散落在聊天和文档，难以判断停在哪里。' },
      { title: '追逻辑', body: '研究思路与证据逐渐断裂，复盘成本越来越高。' },
      { title: '改表达', body: '论文、报告和汇报反复整理同一批研究材料。' },
    ],
    fragmentTitle: '工具很多，研究状态仍靠人搬运',
    fragmentSources: ['文献与数据库', '代码仓库', '实验与计算', '表格与数据', '论文与报告', '聊天与任务'],
    fragmentResearcher: '研究者反复搬运',
    fragmentGap: '上下文、证据关系与下一步被割裂',
    realityThesis: '问题不在于没有 AI，而在于缺少一个能够承载研究过程的系统。',
    loopNumber: '02',
    loopLabel: 'RESEARCH LOOP',
    loopTitle: ['科研不是一次性 Workflow', '而是 Research Loop'],
    loopBody: '结果不是终点，而是下一轮研究的输入。ScienceX 保存研究状态并执行经过授权的任务；研究者决定证据是否成立，以及下一步往哪里走。',
    loopDiagramLabel: '从研究问题到下一轮问题的研究闭环',
    loopNodes: [
      { title: '研究问题', subtitle: 'Question' },
      { title: '候选假设', subtitle: 'Hypothesis' },
      { title: '证据与数据', subtitle: 'Evidence' },
      { title: '实验 / 计算', subtitle: 'Experiment' },
      { title: '结果与边界', subtitle: 'Result' },
      { title: '下一轮问题', subtitle: 'Next question' },
    ],
    loopCenter: 'Research Loop',
    loopCenterBody: '证据更新研究状态',
    memoryTitle: 'Research Memory',
    memoryBody: '研究目标 · 候选假设 · 数据版本 · 证据关系 · 关键决策 · 结果 · 未解决问题',
    loopBoundary: '当前闭环由研究者驱动。ScienceX 协助执行、记录与重放，不替代最终科学判断。',
    maturityNumber: '03',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: '从回答问题，到持续推进研究',
    maturityBody: '产品能力与长期愿景分开表达。ScienceX 当前提供 Research Assistant 能力，后续阶段才逐步走向更完整的 Research Agent。',
    stages: [
      {
        tag: 'NOW',
        badge: '当前可用',
        title: 'Research Assistant',
        body: '研究线程、本地项目、科研 Skills、数据版本、确定性分析、证据与重放。',
        logic: '保存上下文 · 执行与记录',
      },
      {
        tag: 'NEXT',
        badge: '下一阶段',
        title: 'Research Agent',
        body: '更完整地组织计划、执行和验证，并在人工确认后更新研究状态。',
        logic: '计划 → 执行 → 验证',
      },
      {
        tag: 'VISION',
        badge: '长期愿景',
        title: 'AI Scientist',
        body: '让结果持续影响候选假设、实验设计和后续研究方向。',
        logic: 'Hypothesis → Evidence → Next',
      },
    ],
    caseNumber: '04',
    caseLabel: 'RUNNABLE EVIDENCE',
    caseTitle: '一条可以实际运行和重放的研究链路',
    caseBody: '现有的细胞活力教学案例在本地生成模拟数据，完成版本化实验设计、4PL 分析、技术证据评估和结果重放。它也保留失败与证据不足，而不是只展示成功结果。',
    caseFacts: [
      ['03 MIN', '本地教学案例'],
      ['24 WELLS', '带版本的实验设计'],
      ['SHA-256', '输入与产物哈希'],
      ['REPLAY', '固定原始版本重放'],
    ],
    scenariosTitle: '四个真实运行场景',
    scenarios: [
      ['正常剂量反应', '完成分析并生成 3 个产物', 'passed'],
      ['数据更新', '旧版本仍可固定重放', 'verified'],
      ['缺孔输入', '明确失败，不静默补值', 'blocked'],
      ['弱响应', '运行完成，技术证据尚无定论', 'review'],
    ],
    simulationNote: '模拟数据，仅用于产品教学；不代表真实药效、湿实验验证或科学结论。',
    mechanismNumber: '05',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['ScienceX 如何承载', '一次研究推进'],
    mechanismBody: '模型负责推理。ScienceX 负责读取研究状态、组织执行能力、保存运行证据，并把关键判断交还给研究者。',
    mechanismAria: 'ScienceX 研究运行机制',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: '读取研究问题、研究线程与当前证据。' },
      { code: '02', title: 'Plan', body: '拆解任务，确定下一步执行路径。' },
      { code: '03', title: 'Act', body: '调用本机已安装且获得授权的能力。' },
      { code: '04', title: 'Verify', body: '检查输入、运行结果、告警与产物。' },
      { code: '05', title: 'Learn', body: '经研究者确认后保留关键研究状态。' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: '自动化执行不等于科学结论；关键证据仍需人工复核。',
    capabilitiesNumber: '06',
    capabilitiesLabel: 'SKILLS · TOOLS · MCP',
    capabilitiesTitle: ['能力被清楚定义', '环境在授权后连接'],
    capabilitiesBody: 'Skills 描述任务应该如何完成；Tools 与 MCP 把已配置的本地文件、代码、模型和外部服务接入执行过程。',
    skillsTitle: 'Skills 定义任务能力',
    skillsBody: '按研究任务选择已安装、可审阅的工作流。',
    skills: [
      { code: 'D', title: 'Discover', body: '文献检索与资料发现' },
      { code: 'R', title: 'Reason', body: '假设整理、比较与证据分析' },
      { code: 'C', title: 'Create', body: '代码、报告、图表与研究材料' },
      { code: 'V', title: 'Verify', body: '数据、引用和产物复核' },
      { code: 'M', title: 'Remember', body: '研究线程与项目上下文' },
    ],
    toolsTitle: 'Tools / MCP 连接执行环境',
    toolsBody: '连接范围取决于用户已经安装、配置并授权的能力。',
    tools: [
      { title: '本地文件', body: 'PDF / CSV / 项目目录' },
      { title: '代码与终端', body: '仓库 / 命令 / 脚本' },
      { title: '模型提供商', body: '已配置的推理模型' },
      { title: 'MCP 服务', body: '已启用的扩展工具' },
      { title: '数据源', body: '经授权的数据库与服务' },
      { title: '计算环境', body: '本机已有的计算能力' },
    ],
    capabilityCenter: 'ScienceX Agent',
    capabilityBoundary: 'ScienceX 不会默认获得外部系统访问权；可用范围取决于本机配置、连接状态与权限。',
    humanNumber: '07',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX 负责执行和记录', '研究者负责科学判断'],
    humanIntro: '高风险操作需要授权，关键证据需要人工复核。AI 审阅由研究者主动发送，不能替代湿实验、统计审查或领域判断。',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['检索、阅读与整理', '编码、计算与比较', '执行获得授权的工具', '保存过程和候选假设'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['提出重要研究问题', '审核方案与关键证据', '判断结果是否成立', '决定下一轮研究方向'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · 研究者发起、授权、复核并作出最终判断',
    finalNumber: '08',
    finalTitle: '从一条可追溯的研究链路开始',
    finalBody: '在自己的设备上创建研究项目，保留数据版本、分析过程与研究产物。',
    source: '查看源代码',
  },
  en: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · TRACEABLE',
    title: ['Questions to evidence.', 'Evidence to next steps.'],
    intro: 'ScienceX is an open-source, local-first AI workbench for research. It preserves context, calls authorized capabilities, and keeps dataset versions, analysis runs, and artifacts on one traceable path.',
    download: 'Download ScienceX',
    demo: 'Try the 3-minute example',
    loopLink: 'Explore the Research Loop',
    releaseNote: 'Check each Release for the latest included research features',
    trustLabel: 'ScienceX product attributes',
    trust: ['Local data', 'Open source', 'Cross-platform desktop'],
    proofAria: 'ScienceX simulated cell-viability teaching example',
    proofLabel: 'BUILT-IN EXAMPLE · SIMULATED DATA',
    proofQuestionLabel: 'Research question',
    proofQuestion: 'Does SX-101 reduce HepG2 relative viability as concentration increases?',
    proofDataset: 'Pinned dataset version',
    proofRun: 'Deterministic 4PL analysis',
    proofEvidence: 'Technical evidence',
    proofVerdict: 'Supported',
    proofIc50: 'Relative IC50',
    proofReplay: 'Replay verified',
    proofArtifacts: '3 research artifacts',
    navLabel: 'Homepage sections',
    navItems: [
      ['Problem', '#research-reality'],
      ['Loop', '#research-loop'],
      ['Evidence', '#runnable-evidence'],
      ['Runtime', '#mechanism'],
      ['Capabilities', '#capabilities'],
      ['Boundary', '#human-in-the-loop'],
    ],
    realityNumber: '01',
    realityLabel: 'ATTENTION',
    realityTitle: ['Information is abundant.', 'Researcher attention is scarce.'],
    realityBody: 'Research work is split across papers, code, data, laboratory software, and writing tools. The expensive part is repeatedly moving information, rebuilding context, and tracing how evidence supports a decision.',
    realitySignals: [
      { title: 'Find sources', body: 'Papers, data, and tools are scattered across systems.' },
      { title: 'Track progress', body: 'Tasks live in chats and documents, hiding the next step.' },
      { title: 'Trace logic', body: 'Hypotheses and evidence drift apart as work continues.' },
      { title: 'Rewrite outputs', body: 'The same research material is rebuilt for every format.' },
    ],
    fragmentTitle: 'More tools still leave people moving research state',
    fragmentSources: ['Literature & databases', 'Code repositories', 'Experiments & compute', 'Tables & data', 'Papers & reports', 'Chats & tasks'],
    fragmentResearcher: 'Researcher moves context',
    fragmentGap: 'Context, evidence, and next steps become disconnected',
    realityThesis: 'The gap is not another AI model. It is a system that can carry the research process.',
    loopNumber: '02',
    loopLabel: 'RESEARCH LOOP',
    loopTitle: ['Research is not one-way.', 'Evidence keeps the loop moving.'],
    loopBody: 'A result is input for the next research cycle. ScienceX preserves research state and executes authorized work. Researchers decide what the evidence supports and where the work goes next.',
    loopDiagramLabel: 'Research loop from a question to the next question',
    loopNodes: [
      { title: 'Question', subtitle: 'Research focus' },
      { title: 'Hypothesis', subtitle: 'Candidate explanation' },
      { title: 'Evidence', subtitle: 'Data and sources' },
      { title: 'Experiment', subtitle: 'Experiment / compute' },
      { title: 'Result', subtitle: 'Outcome and boundary' },
      { title: 'Next question', subtitle: 'Continue the loop' },
    ],
    loopCenter: 'Research Loop',
    loopCenterBody: 'Evidence updates research state',
    memoryTitle: 'Research Memory',
    memoryBody: 'Goals · candidate hypotheses · dataset versions · evidence relations · decisions · results · open questions',
    loopBoundary: 'The current loop is researcher-driven. ScienceX assists execution, recording, and replay; it does not replace the final scientific judgment.',
    maturityNumber: '03',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: 'From answering a question to advancing research',
    maturityBody: 'Current capabilities and long-term direction stay distinct. ScienceX provides a Research Assistant today; a more complete Research Agent belongs to the next stage.',
    stages: [
      {
        tag: 'NOW',
        badge: 'Available now',
        title: 'Research Assistant',
        body: 'Research threads, local projects, research Skills, dataset versions, deterministic analysis, evidence, and replay.',
        logic: 'Preserve context · execute · record',
      },
      {
        tag: 'NEXT',
        badge: 'Next stage',
        title: 'Research Agent',
        body: 'Organize planning, execution, and verification more completely, then update research state after human confirmation.',
        logic: 'Plan → Act → Verify',
      },
      {
        tag: 'VISION',
        badge: 'Long-term vision',
        title: 'AI Scientist',
        body: 'Let results continue to shape candidate hypotheses, experiment design, and the next research direction.',
        logic: 'Hypothesis → Evidence → Next',
      },
    ],
    caseNumber: '04',
    caseLabel: 'RUNNABLE EVIDENCE',
    caseTitle: 'A research path you can run and replay',
    caseBody: 'The current cell-viability teaching example generates simulated data locally, then runs a versioned assay design, deterministic 4PL analysis, technical-evidence evaluation, and replay. It preserves failed and inconclusive outcomes instead of showing only success.',
    caseFacts: [
      ['03 MIN', 'Local teaching example'],
      ['24 WELLS', 'Versioned assay design'],
      ['SHA-256', 'Input and artifact hashes'],
      ['REPLAY', 'Pinned-version replay'],
    ],
    scenariosTitle: 'Four actual run scenarios',
    scenarios: [
      ['Dose response', 'Completes analysis and creates 3 artifacts', 'passed'],
      ['Changed data', 'The pinned old version still replays', 'verified'],
      ['Missing well', 'Fails explicitly without filling values', 'blocked'],
      ['Weak response', 'Run completes with inconclusive evidence', 'review'],
    ],
    simulationNote: 'Simulated teaching data. It does not establish efficacy, wet-lab validation, or a scientific conclusion.',
    mechanismNumber: '05',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['How ScienceX carries', 'research forward'],
    mechanismBody: 'Models provide reasoning. ScienceX reads research state, organizes execution capabilities, preserves run evidence, and returns important judgments to the researcher.',
    mechanismAria: 'ScienceX research runtime mechanism',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: 'Read the question, research thread, and current evidence.' },
      { code: '02', title: 'Plan', body: 'Break down the task and define the next execution path.' },
      { code: '03', title: 'Act', body: 'Call capabilities installed locally and explicitly authorized.' },
      { code: '04', title: 'Verify', body: 'Inspect inputs, results, warnings, and artifacts.' },
      { code: '05', title: 'Learn', body: 'Preserve key research state after researcher confirmation.' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: 'Automated execution is not a scientific conclusion. Important evidence still requires human review.',
    capabilitiesNumber: '06',
    capabilitiesLabel: 'SKILLS · TOOLS · MCP',
    capabilitiesTitle: ['Capabilities stay explicit.', 'Environments connect with permission.'],
    capabilitiesBody: 'Skills describe how work should be done. Tools and MCP connect configured local files, code, models, and external services to the execution path.',
    skillsTitle: 'Skills define task capabilities',
    skillsBody: 'Choose installed, reviewable workflows for the research task.',
    skills: [
      { code: 'D', title: 'Discover', body: 'Literature search and source discovery' },
      { code: 'R', title: 'Reason', body: 'Hypothesis comparison and evidence analysis' },
      { code: 'C', title: 'Create', body: 'Code, reports, figures, and research material' },
      { code: 'V', title: 'Verify', body: 'Data, citation, and artifact review' },
      { code: 'M', title: 'Remember', body: 'Research threads and project context' },
    ],
    toolsTitle: 'Tools / MCP connect execution environments',
    toolsBody: 'Connections depend on capabilities the user has installed, configured, and authorized.',
    tools: [
      { title: 'Local files', body: 'PDF / CSV / project directories' },
      { title: 'Code & terminal', body: 'Repositories / commands / scripts' },
      { title: 'Model providers', body: 'Configured reasoning models' },
      { title: 'MCP services', body: 'Enabled extension tools' },
      { title: 'Data sources', body: 'Authorized databases and services' },
      { title: 'Compute', body: 'Existing local compute capabilities' },
    ],
    capabilityCenter: 'ScienceX Agent',
    capabilityBoundary: 'ScienceX has no default access to external systems. Availability depends on local configuration, connection state, and permission.',
    humanNumber: '07',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX executes and records.', 'Researchers make scientific judgments.'],
    humanIntro: 'High-risk actions require authorization, and important evidence requires human review. Researchers send AI review prompts explicitly. AI does not replace wet-lab work, statistical review, or domain judgment.',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['Search, read, and organize', 'Code, compute, and compare', 'Execute authorized tools', 'Preserve process and candidate hypotheses'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['Ask important research questions', 'Review protocols and critical evidence', 'Decide what the results support', 'Choose the next research direction'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · researchers initiate, authorize, review, and make the final judgment',
    finalNumber: '08',
    finalTitle: 'Start with one traceable research path',
    finalBody: 'Create a research project on your own device and preserve its dataset versions, analysis process, and artifacts.',
    source: 'View source',
  },
} as const

export type HomeCopy = (typeof HOME_COPY)[keyof typeof HOME_COPY]
