export const HOME_COPY = {
  zh: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · TRACEABLE',
    title: ['ScienceX', '科研工作台'],
    intro: 'ScienceX 是开源、本地优先的 AI 科研工作台。它保存研究上下文，调用经过授权的能力，并把数据版本、分析运行和研究产物留在同一条可追溯链路中。',
    download: '下载 ScienceX',
    demo: '体验 3 分钟案例',
    loopLink: '了解 Research Loop',
    releaseNote: '最新科研功能请以 Release 说明为准',
    trustLabel: 'ScienceX 产品特征',
    trust: ['本地数据', '开放源码', '跨平台桌面端'],
    proofAria: 'ScienceX 模拟细胞活力教学案例',
    proofLabel: '内置案例 · 模拟数据',
    proofQuestionLabel: '研究问题',
    proofQuestion: 'SX-101 是否随浓度升高降低 HepG2 细胞的相对活力？',
    proofDataset: '锁定数据版本',
    proofRun: '确定性 4PL 分析',
    proofEvidence: '技术证据',
    proofVerdict: '支持',
    proofIc50: '相对 IC50',
    proofReplay: '重放验证一致',
    proofArtifacts: '3 个研究产物',
    navLabel: '首页章节',
    navItems: [
      ['场景', '#research-reality'],
      ['产品', '#product-proof'],
      ['闭环', '#research-loop'],
      ['案例', '#runnable-evidence'],
      ['Skills', '#capabilities'],
      ['边界', '#human-in-the-loop'],
      ['开始', '#start'],
    ],
    realityNumber: '01',
    realityLabel: 'DAILY RESEARCH',
    realityTitle: ['四件重复工作交给 ScienceX', '关键判断留给研究者'],
    realityBody: '科研最稀缺的不是信息，而是研究者的注意力。ScienceX 接手耗时、重复、可检查的工作，把阅读、判断和研究方向交还给研究者。',
    scenarioOutputLabel: '形成产物',
    scenarioOwnerLabel: '研究者保留',
    scenarioPromptLabel: '示例指令',
    realitySignals: [
      {
        title: '搜资料',
        body: '按范围、来源、年份和验收格式检索并初筛。',
        output: '带出处的文献表与证据摘要',
        owner: '决定精读什么、相信什么',
        prompt: '检索近三年关于 X 的代表论文，每条附出处。',
      },
      {
        title: '跟进度',
        body: '把计划中、进行中、已完成和搁置事项归入研究线程。',
        output: '进度板、阶段总结与下一步清单',
        owner: '决定优先级和研究方向',
        prompt: '汇总本周推进、阻塞原因和下周最重要的三步。',
      },
      {
        title: '追逻辑',
        body: '围绕前提、证据、反例和适用边界逐句追问。',
        output: '论证缺口与待验证问题',
        owner: '回答关键问题、修正论证',
        prompt: '扮演严格评审，追问这段论证凭什么成立。',
      },
      {
        title: '改表达',
        body: '纠错、润色、统一术语，并保留修改类型与理由。',
        output: '修改建议、差异记录与风格档案',
        owner: '保留观点、结论和个人风格',
        prompt: '逐处给出原句、改句和理由，不替我改写结论。',
      },
    ],
    realityThesis: '提速的关键不是让 AI 代替思考，而是让它接手重复工作，并把证据和下一步留在研究过程里。',
    productNumber: '02',
    productLabel: 'PRODUCT IN USE',
    productTitle: ['不是功能清单', '是正在运行的科研工作台'],
    productBody: '研究项目、研究线程、定时任务与科研 Skills 已经进入同一个桌面工作台。下面展示的是经过裁切和脱敏的 ScienceX 产品界面。',
    productFrames: [
      {
        code: '01',
        label: 'RESEARCH THREAD',
        title: '研究线程承载问题与下一步',
        body: '把研究问题、过程说明、文件和后续行动放在同一条可继续的研究记录中。',
        image: '/images/home/research-thread.webp',
        alt: 'ScienceX 研究线程界面，展示分步骤研究行动和输入框',
      },
      {
        code: '02',
        label: 'SCHEDULED TASKS',
        title: '重复整理可以按计划运行',
        body: '在桌面端创建和管理定时任务；本地任务仅在应用运行、设备保持唤醒时执行。',
        image: '/images/home/scheduled-tasks.webp',
        alt: 'ScienceX 定时任务界面，展示新建任务入口和本地运行提示',
      },
    ],
    productSkillLabel: 'RESEARCH SKILLS',
    productSkillTitle: '方法不是隐藏提示词，而是可查看的能力',
    productSkillBody: '科研 Skills 在产品中独立呈现，研究者可以查看名称、来源和适用边界。',
    productSkillPreview: ['scansci-pdf', 'good-question', 'experiment-design', 'academic-writing', 'papercheck', 'skill-criticagent'],
    productSkillCount: '20',
    productProofNote: '界面随版本持续更新；实际可用能力以当前 Release、本机依赖、连接状态与授权范围为准。',
    loopNumber: '03',
    loopLabel: 'RESEARCH LOOP',
    loopTitle: ['科研不是一次性 Workflow', '而是 Research Loop'],
    loopBody: '结果不是终点，而是下一轮研究的输入。ScienceX 保存研究状态并执行经过授权的任务；研究者决定证据是否成立，以及下一步往哪里走。',
    loopDiagramLabel: '从研究问题到下一轮问题的研究闭环',
    loopNodes: [
      { title: '研究问题', subtitle: 'Question' },
      { title: '候选假设', subtitle: 'Hypothesis' },
      { title: '证据与数据', subtitle: 'Evidence' },
      { title: '实验 / 计算', subtitle: 'Experiment' },
      { title: '结果与边界', subtitle: 'Result' },
      { title: '下一轮问题', subtitle: 'Next question' },
    ],
    loopCenter: 'Research Loop',
    loopCenterBody: '证据更新研究状态',
    memoryTitle: 'Research Memory',
    memoryBody: '研究目标 · 候选假设 · 数据版本 · 证据关系 · 关键决策 · 结果 · 未解决问题',
    loopBoundary: '当前闭环由研究者驱动。ScienceX 协助执行、记录与重放，不替代最终科学判断。',
    maturityNumber: '04',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: '从回答问题，到持续推进研究',
    maturityBody: '产品能力与长期愿景分开表达。ScienceX 当前提供 Research Assistant 能力，后续阶段才逐步走向更完整的 Research Agent。',
    stages: [
      {
        tag: 'NOW',
        badge: '当前可用',
        title: 'Research Assistant',
        body: '研究线程、本地项目、科研 Skills、数据版本、确定性分析、证据与重放。',
        logic: '保存上下文 · 执行与记录',
      },
      {
        tag: 'NEXT',
        badge: '下一阶段',
        title: 'Research Agent',
        body: '更完整地组织计划、执行和验证，并在人工确认后更新研究状态。',
        logic: '计划 → 执行 → 验证',
      },
      {
        tag: 'VISION',
        badge: '长期愿景',
        title: 'AI Scientist',
        body: '让结果持续影响候选假设、实验设计和后续研究方向。',
        logic: 'Hypothesis → Evidence → Next',
      },
    ],
    caseNumber: '05',
    caseLabel: 'RUNNABLE EVIDENCE',
    caseTitle: '一条可以实际运行和重放的研究链路',
    caseBody: '现有的细胞活力教学案例在本地生成模拟数据，完成版本化实验设计、4PL 分析、技术证据评估和结果重放。它也保留失败与证据不足，而不是只展示成功结果。',
    caseFacts: [
      ['03 MIN', '本地教学案例'],
      ['24 WELLS', '带版本的实验设计'],
      ['SHA-256', '输入与产物哈希'],
      ['REPLAY', '固定原始版本重放'],
    ],
    scenariosTitle: '四个真实运行场景',
    scenarios: [
      ['正常剂量反应', '完成分析并生成 3 个产物', 'passed'],
      ['数据更新', '旧版本仍可固定重放', 'verified'],
      ['缺孔输入', '明确失败，不静默补值', 'blocked'],
      ['弱响应', '运行完成，技术证据尚无定论', 'review'],
    ],
    simulationNote: '模拟数据，仅用于产品教学；不代表真实药效、湿实验验证或科学结论。',
    mechanismNumber: '06',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['ScienceX 如何承载', '一次研究推进'],
    mechanismBody: '模型负责推理。ScienceX 负责读取研究状态、组织执行能力、保存运行证据，并把关键判断交还给研究者。',
    mechanismAria: 'ScienceX 研究运行机制',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: '读取研究问题、研究线程与当前证据。' },
      { code: '02', title: 'Plan', body: '拆解任务，确定下一步执行路径。' },
      { code: '03', title: 'Act', body: '调用本机已安装且获得授权的能力。' },
      { code: '04', title: 'Verify', body: '检查输入、运行结果、告警与产物。' },
      { code: '05', title: 'Learn', body: '经研究者确认后保留关键研究状态。' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: '自动化执行不等于科学结论；关键证据仍需人工复核。',
    capabilitiesNumber: '07',
    capabilitiesLabel: 'RESEARCH SKILLS',
    capabilitiesTitle: ['20 个科研 Skills', '把方法带进任务'],
    capabilitiesBody: '当前科研能力按发现、推理、实验、表达、审查和评测组织。它们是可以检查的任务方法；运行条件和外部访问权不会被隐含授予。',
    skillCount: '20',
    skillCountLabel: '个科研 Skills 已集成到 ScienceX',
    skillGroups: [
      {
        code: '01',
        title: '发现与检索',
        body: '找到合适的方法、论文与可核对的来源。',
        skills: ['find-science-skills', 'giiisp-paper-search-apis', 'scansci-pdf'],
      },
      {
        code: '02',
        title: '调研与推理',
        body: '形成候选方向，并用评审式追问暴露缺口。',
        skills: ['sci-employee-deep-research', 'scispark', 'good-question'],
      },
      {
        code: '03',
        title: '研究与实验',
        body: '把研究问题转成设计、数据基线与验证步骤。',
        skills: ['experiment-design', 'research-baseline-builder'],
      },
      {
        code: '04',
        title: '写作与呈现',
        body: '组织论文、图像、幻灯片、视频与课程产物。',
        skills: ['academic-writing', 'scientific-humanization', 'giiisp-scientific-image-generation', 'visual-deck-builder', 'manim-agent', 'practical-course-producer'],
      },
      {
        code: '05',
        title: '审查与记忆',
        body: '检查论文和引用，并保存长期研究上下文。',
        skills: ['thesis-audit-reviewer', 'papercheck', 'cognitive-profile', 'world-threads-entry'],
      },
      {
        code: '06',
        title: '能力评测',
        body: '在采用新工具前检查 MCP 与 Skill 的质量。',
        skills: ['mcp-criticagent', 'skill-criticagent'],
      },
    ],
    environmentsLabel: '授权后连接执行环境',
    environments: [
      { title: '本地文件', body: 'PDF / CSV / 项目目录' },
      { title: '代码与终端', body: '仓库 / 命令 / 脚本' },
      { title: '模型提供商', body: '已配置的推理模型' },
      { title: 'MCP 服务', body: '已启用的扩展工具' },
      { title: '数据源', body: '经授权的数据库与服务' },
      { title: '计算环境', body: '本机已有的计算能力' },
    ],
    skillsBoundary: '“已集成”不等于无条件可运行。部分 Skills 需要本机依赖、外部服务或用户授权；ScienceX 不会默认获得论文库、数据库或其他系统的访问权。',
    skillsGuide: '查看 Skills 使用指南',
    humanNumber: '08',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX 负责执行和记录', '研究者负责科学判断'],
    humanIntro: '高风险操作需要授权，关键证据需要人工复核。AI 审阅由研究者主动发送，不能替代湿实验、统计审查或领域判断。',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['检索、阅读与整理', '编码、计算与比较', '执行获得授权的工具', '保存过程和候选假设'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['提出重要研究问题', '审核方案与关键证据', '判断结果是否成立', '决定下一轮研究方向'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · 研究者发起、授权、复核并作出最终判断',
    guardrailsLabel: 'ScienceX 使用边界',
    guardrails: ['AI 纠错，不替你写', 'AI 初筛，不替你读', '数据有边界', '不夸大结果与结论'],
    finalNumber: '09',
    finalTitle: '从一条可追溯的研究链路开始',
    finalBody: '在自己的设备上创建研究项目，用一个真实问题完成第一次研究推进。',
    startSteps: ['打开本地研究项目', '说清范围、输出格式和验收条件', '检查来源、产物与下一步建议'],
    starterPromptLabel: '可以直接开始的示例',
    starterPrompt: '检索近三年关于 X 的代表论文，按方法、数据、结论和局限整理成表，每条附出处；先给 10 篇，找不到就明确说明，不要编造。',
    source: '查看源代码',
  },
  en: {
    eyebrow: 'OPEN SOURCE · LOCAL FIRST · TRACEABLE',
    title: ['Questions to evidence.', 'Evidence to next steps.'],
    intro: 'ScienceX is an open-source, local-first AI workbench for research. It preserves context, calls authorized capabilities, and keeps dataset versions, analysis runs, and artifacts on one traceable path.',
    download: 'Download ScienceX',
    demo: 'Try the 3-minute example',
    loopLink: 'Explore the Research Loop',
    releaseNote: 'Check each Release for the latest included research features',
    trustLabel: 'ScienceX product attributes',
    trust: ['Local data', 'Open source', 'Cross-platform desktop'],
    proofAria: 'ScienceX simulated cell-viability teaching example',
    proofLabel: 'BUILT-IN EXAMPLE · SIMULATED DATA',
    proofQuestionLabel: 'Research question',
    proofQuestion: 'Does SX-101 reduce HepG2 relative viability as concentration increases?',
    proofDataset: 'Pinned dataset version',
    proofRun: 'Deterministic 4PL analysis',
    proofEvidence: 'Technical evidence',
    proofVerdict: 'Supported',
    proofIc50: 'Relative IC50',
    proofReplay: 'Replay verified',
    proofArtifacts: '3 research artifacts',
    navLabel: 'Homepage sections',
    navItems: [
      ['Use cases', '#research-reality'],
      ['Product', '#product-proof'],
      ['Loop', '#research-loop'],
      ['Evidence', '#runnable-evidence'],
      ['Skills', '#capabilities'],
      ['Boundary', '#human-in-the-loop'],
      ['Start', '#start'],
    ],
    realityNumber: '01',
    realityLabel: 'DAILY RESEARCH',
    realityTitle: ['Give repetitive work to ScienceX.', 'Keep judgment with the researcher.'],
    realityBody: 'Information is abundant; researcher attention is scarce. ScienceX takes on time-consuming, repeatable, reviewable work while researchers retain close reading, judgment, and direction.',
    scenarioOutputLabel: 'Artifact',
    scenarioOwnerLabel: 'Researcher keeps',
    scenarioPromptLabel: 'Example prompt',
    realitySignals: [
      {
        title: 'Find sources',
        body: 'Search and screen by scope, source, date, and acceptance format.',
        output: 'A sourced paper table and evidence brief',
        owner: 'What deserves close reading and trust',
        prompt: 'Find representative papers on X from the last three years. Cite every item.',
      },
      {
        title: 'Track progress',
        body: 'Organize planned, active, completed, and paused work in the research thread.',
        output: 'Progress board, review, and next-step list',
        owner: 'Priority and research direction',
        prompt: 'Summarize this week, blockers, and the three most important next steps.',
      },
      {
        title: 'Trace logic',
        body: 'Interrogate premises, evidence, counterexamples, and scope one claim at a time.',
        output: 'Argument gaps and questions to verify',
        owner: 'Answers and changes to the argument',
        prompt: 'Act as a rigorous reviewer and ask what makes each claim hold.',
      },
      {
        title: 'Refine expression',
        body: 'Correct, polish, and normalize terms while recording each type of change.',
        output: 'Suggestions, diffs, and a style record',
        owner: 'Position, conclusion, and personal voice',
        prompt: 'Show original, revision, and reason. Do not rewrite my conclusion.',
      },
    ],
    realityThesis: 'Speed comes from letting AI take repetitive work while evidence, judgment, and the next step remain visible in the research process.',
    productNumber: '02',
    productLabel: 'PRODUCT IN USE',
    productTitle: ['Not a feature list.', 'A research workbench already in use.'],
    productBody: 'Research projects, focused threads, scheduled tasks, and research Skills now live in the same desktop workbench. These are cropped, privacy-safe views from ScienceX.',
    productFrames: [
      {
        code: '01',
        label: 'RESEARCH THREAD',
        title: 'A thread carries the question forward',
        body: 'Keep the research question, process notes, files, and proposed actions in one record that can continue.',
        image: '/images/home/research-thread.webp',
        alt: 'ScienceX research thread showing structured next actions and the prompt composer',
      },
      {
        code: '02',
        label: 'SCHEDULED TASKS',
        title: 'Recurring work can run on a schedule',
        body: 'Create and manage scheduled desktop tasks. Local tasks run only while the app is open and the device stays awake.',
        image: '/images/home/scheduled-tasks.webp',
        alt: 'ScienceX scheduled tasks screen with a create-task action and local runtime notice',
      },
    ],
    productSkillLabel: 'RESEARCH SKILLS',
    productSkillTitle: 'Methods are visible capabilities, not hidden prompts',
    productSkillBody: 'Research Skills appear independently in the product so researchers can inspect their names, sources, and operating boundaries.',
    productSkillPreview: ['scansci-pdf', 'good-question', 'experiment-design', 'academic-writing', 'papercheck', 'skill-criticagent'],
    productSkillCount: '20',
    productProofNote: 'The interface evolves by release. Actual availability depends on the current release, local dependencies, connection state, and authorization.',
    loopNumber: '03',
    loopLabel: 'RESEARCH LOOP',
    loopTitle: ['Research is not one-way.', 'Evidence keeps the loop moving.'],
    loopBody: 'A result is input for the next research cycle. ScienceX preserves research state and executes authorized work. Researchers decide what the evidence supports and where the work goes next.',
    loopDiagramLabel: 'Research loop from a question to the next question',
    loopNodes: [
      { title: 'Question', subtitle: 'Research focus' },
      { title: 'Hypothesis', subtitle: 'Candidate explanation' },
      { title: 'Evidence', subtitle: 'Data and sources' },
      { title: 'Experiment', subtitle: 'Experiment / compute' },
      { title: 'Result', subtitle: 'Outcome and boundary' },
      { title: 'Next question', subtitle: 'Continue the loop' },
    ],
    loopCenter: 'Research Loop',
    loopCenterBody: 'Evidence updates research state',
    memoryTitle: 'Research Memory',
    memoryBody: 'Goals · candidate hypotheses · dataset versions · evidence relations · decisions · results · open questions',
    loopBoundary: 'The current loop is researcher-driven. ScienceX assists execution, recording, and replay; it does not replace the final scientific judgment.',
    maturityNumber: '04',
    maturityLabel: 'CAPABILITY MATURITY',
    maturityTitle: 'From answering a question to advancing research',
    maturityBody: 'Current capabilities and long-term direction stay distinct. ScienceX provides a Research Assistant today; a more complete Research Agent belongs to the next stage.',
    stages: [
      {
        tag: 'NOW',
        badge: 'Available now',
        title: 'Research Assistant',
        body: 'Research threads, local projects, research Skills, dataset versions, deterministic analysis, evidence, and replay.',
        logic: 'Preserve context · execute · record',
      },
      {
        tag: 'NEXT',
        badge: 'Next stage',
        title: 'Research Agent',
        body: 'Organize planning, execution, and verification more completely, then update research state after human confirmation.',
        logic: 'Plan → Act → Verify',
      },
      {
        tag: 'VISION',
        badge: 'Long-term vision',
        title: 'AI Scientist',
        body: 'Let results continue to shape candidate hypotheses, experiment design, and the next research direction.',
        logic: 'Hypothesis → Evidence → Next',
      },
    ],
    caseNumber: '05',
    caseLabel: 'RUNNABLE EVIDENCE',
    caseTitle: 'A research path you can run and replay',
    caseBody: 'The current cell-viability teaching example generates simulated data locally, then runs a versioned assay design, deterministic 4PL analysis, technical-evidence evaluation, and replay. It preserves failed and inconclusive outcomes instead of showing only success.',
    caseFacts: [
      ['03 MIN', 'Local teaching example'],
      ['24 WELLS', 'Versioned assay design'],
      ['SHA-256', 'Input and artifact hashes'],
      ['REPLAY', 'Pinned-version replay'],
    ],
    scenariosTitle: 'Four actual run scenarios',
    scenarios: [
      ['Dose response', 'Completes analysis and creates 3 artifacts', 'passed'],
      ['Changed data', 'The pinned old version still replays', 'verified'],
      ['Missing well', 'Fails explicitly without filling values', 'blocked'],
      ['Weak response', 'Run completes with inconclusive evidence', 'review'],
    ],
    simulationNote: 'Simulated teaching data. It does not establish efficacy, wet-lab validation, or a scientific conclusion.',
    mechanismNumber: '06',
    mechanismLabel: 'HOW IT WORKS',
    mechanismTitle: ['How ScienceX carries', 'research forward'],
    mechanismBody: 'Models provide reasoning. ScienceX reads research state, organizes execution capabilities, preserves run evidence, and returns important judgments to the researcher.',
    mechanismAria: 'ScienceX research runtime mechanism',
    mechanismSteps: [
      { code: '01', title: 'Understand', body: 'Read the question, research thread, and current evidence.' },
      { code: '02', title: 'Plan', body: 'Break down the task and define the next execution path.' },
      { code: '03', title: 'Act', body: 'Call capabilities installed locally and explicitly authorized.' },
      { code: '04', title: 'Verify', body: 'Inspect inputs, results, warnings, and artifacts.' },
      { code: '05', title: 'Learn', body: 'Preserve key research state after researcher confirmation.' },
    ],
    mechanismMemoryLabel: 'STATE LAYER',
    mechanismBoundary: 'Automated execution is not a scientific conclusion. Important evidence still requires human review.',
    capabilitiesNumber: '07',
    capabilitiesLabel: 'RESEARCH SKILLS',
    capabilitiesTitle: ['20 research Skills.', 'Methods brought into the task.'],
    capabilitiesBody: 'Current research capabilities are organized around discovery, reasoning, experiments, expression, review, and evaluation. They are inspectable methods; runtime requirements and external access are never implied.',
    skillCount: '20',
    skillCountLabel: 'research Skills integrated with ScienceX',
    skillGroups: [
      {
        code: '01',
        title: 'Discovery & search',
        body: 'Find methods, papers, and sources that can be checked.',
        skills: ['find-science-skills', 'giiisp-paper-search-apis', 'scansci-pdf'],
      },
      {
        code: '02',
        title: 'Research & reasoning',
        body: 'Generate candidate directions and expose gaps through reviewer-style questions.',
        skills: ['sci-employee-deep-research', 'scispark', 'good-question'],
      },
      {
        code: '03',
        title: 'Study & experiment',
        body: 'Turn a research question into a design, data baseline, and verification steps.',
        skills: ['experiment-design', 'research-baseline-builder'],
      },
      {
        code: '04',
        title: 'Writing & presentation',
        body: 'Organize papers, figures, slides, videos, and course artifacts.',
        skills: ['academic-writing', 'scientific-humanization', 'giiisp-scientific-image-generation', 'visual-deck-builder', 'manim-agent', 'practical-course-producer'],
      },
      {
        code: '05',
        title: 'Review & memory',
        body: 'Review papers and citations while preserving long-running research context.',
        skills: ['thesis-audit-reviewer', 'papercheck', 'cognitive-profile', 'world-threads-entry'],
      },
      {
        code: '06',
        title: 'Capability evaluation',
        body: 'Assess MCP servers and Skills before adopting new tools.',
        skills: ['mcp-criticagent', 'skill-criticagent'],
      },
    ],
    environmentsLabel: 'Execution environments connect after authorization',
    environments: [
      { title: 'Local files', body: 'PDF / CSV / project folders' },
      { title: 'Code & terminal', body: 'Repositories / commands / scripts' },
      { title: 'Model providers', body: 'Configured reasoning models' },
      { title: 'MCP services', body: 'Enabled extension tools' },
      { title: 'Data sources', body: 'Authorized databases and services' },
      { title: 'Compute', body: 'Existing local compute capabilities' },
    ],
    skillsBoundary: 'Integrated does not mean universally runnable. Some Skills require local dependencies, external services, or user authorization. ScienceX has no default access to paper libraries, databases, or other systems.',
    skillsGuide: 'Read the Skills guide',
    humanNumber: '08',
    humanLabel: 'HUMAN IN THE LOOP',
    humanTitle: ['ScienceX executes and records.', 'Researchers make scientific judgments.'],
    humanIntro: 'High-risk actions require authorization, and important evidence requires human review. Researchers send AI review prompts explicitly. AI does not replace wet-lab work, statistical review, or domain judgment.',
    sciencexRole: 'ScienceX',
    sciencexRoleLabel: 'EXECUTION',
    sciencexTasks: ['Search, read, and organize', 'Code, compute, and compare', 'Execute authorized tools', 'Preserve process and candidate hypotheses'],
    researcherRole: 'Researcher',
    researcherRoleLabel: 'JUDGMENT',
    researcherTasks: ['Ask important research questions', 'Review protocols and critical evidence', 'Decide what the results support', 'Choose the next research direction'],
    operatingModel: 'CURRENT OPERATING MODEL',
    operatingModelBody: 'Human-driven Research Loop · researchers initiate, authorize, review, and make the final judgment',
    guardrailsLabel: 'ScienceX operating boundaries',
    guardrails: ['AI corrects; it does not ghostwrite', 'AI screens; it does not replace close reading', 'Data has boundaries', 'Never inflate results or conclusions'],
    finalNumber: '09',
    finalTitle: 'Start with one traceable research path',
    finalBody: 'Create a project on your own device and move one real research question forward.',
    startSteps: ['Open a local research project', 'Define scope, output format, and acceptance criteria', 'Inspect sources, artifacts, and proposed next steps'],
    starterPromptLabel: 'A prompt you can start with',
    starterPrompt: 'Find representative papers on X from the last three years. Organize method, data, conclusion, and limitations in a table with a source for every item. Start with 10; say clearly when evidence is unavailable, and do not fabricate.',
    source: 'View source',
  },
} as const

export type HomeCopy = (typeof HOME_COPY)[keyof typeof HOME_COPY]
